namespace ZelosHR.Api.Shared.Constants;

/// <summary>Query parameter names (snake_case on the wire). No resource IDs in URL paths.</summary>
public static class PlatformQueryParams
{
    public const string Search = "search";
    public const string Page = "page";
    public const string Size = "size";
    public const string SortBy = "sort_by";
    public const string SortOrder = "sort_order";
    public const string Status = "status";
    public const string FromDate = "from_date";
    public const string ToDate = "to_date";
    public const string StartDate = "start_date";
    public const string EndDate = "end_date";
    public const string SubmittedFromDate = "submitted_from_date";
    public const string SubmittedToDate = "submitted_to_date";
    public const string AnchorDate = "anchor_date";
    public const string EmployeeCode = "employee_code";
    public const string ApprovalStage = "approval_stage";
    public const string AccrualMethod = "accrual_method";
    public const string IsPaid = "is_paid";
    public const string ActiveOnly = "active_only";
    public const string IncludeArchived = "include_archived";
    public const string IncludeInactive = "include_inactive";
    public const string IncludeDeleted = "include_deleted";
    public const string Year = "year";
    public const string View = "view";
    public const string Tab = "tab";
    public const string FieldKey = "field_key";
    public const string FieldType = "field_type";
    public const string EntityType = "entity_type";
    public const string EntityId = "entity_id";
    public const string IsRequired = "is_required";
    public const string IsSensitive = "is_sensitive";
    public const string IsFilterable = "is_filterable";
    public const string IsSearchable = "is_searchable";
    public const string IsActive = "is_active";
    public const string SectionName = "section_name";
    public const string ChangeType = "change_type";
    public const string ChangedBy = "changed_by";
    public const string ChangedFrom = "changed_from";
    public const string ChangedTo = "changed_to";
    public const string EmploymentStatus = "employment_status";
    public const string EmploymentType = "employment_type";
    public const string WorkLocation = "work_location";
    public const string LifecycleState = "lifecycle_state";
    public const string StatusFilter = "status_filter";

    public const string Severity = "severity";
    public const string Action = "action";
    public const string Actor = "actor";
    public const string Category = "category";
    public const string EventType = "event_type";
    public const string Urgency = "urgency";
    public const string Department = "department";
    public const string Branch = "branch";
    public const string Date = "date";
    public const string Label = "label";

    public const string EmployeeId = "employee_id";
    public const string CurrencyId = "currency_id";
    public const string EducationId = "education_id";
    public const string CertificationId = "certification_id";
    public const string DocumentId = "document_id";
    public const string AttendanceId = "attendance_id";
    public const string LeaveRequestId = "leave_request_id";
    public const string LeaveBalanceId = "leave_balance_id";
    public const string LeaveTypeId = "leave_type_id";
    public const string HolidayId = "holiday_id";
    public const string CountryId = "country_id";
    public const string Country = "country";
    public const string LifecycleEventId = "lifecycle_event_id";
    public const string AuditLogId = "audit_log_id";
    public const string RecruitmentId = "recruitment_id";
    public const string OnboardingId = "onboarding_id";
    public const string PerformanceId = "performance_id";
    public const string DisciplinaryId = "disciplinary_id";
    public const string CustomFieldId = "custom_field_id";
    public const string DepartmentId = "department_id";
    public const string BranchId = "branch_id";
}
