#!/usr/bin/env bash
# Pull dev Container App DB connection into scripts/local-dev/live-db.env (gitignored).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="${ROOT}/scripts/local-dev/live-db.env"
RG="${AZURE_RESOURCE_GROUP:-trovesuite-dev-appservers-rg}"
APP="${AZURE_CONTAINER_APP:-trovesuite-dev-zeloshr-ca}"

if ! command -v az >/dev/null 2>&1; then
  echo "az CLI is required. Run: az login" >&2
  exit 1
fi

CONN="$(az containerapp show \
  --name "$APP" \
  --resource-group "$RG" \
  --query "properties.template.containers[0].env[?name=='App__ConnectionString'].value | [0]" \
  -o tsv 2>/dev/null || true)"

if [[ -z "$CONN" ]]; then
  echo "Could not read App__ConnectionString from $APP in $RG" >&2
  exit 1
fi

JWT_FILE="${ROOT}/scripts/local-dev/.jwt-secret.local"
JWT_LINE=""
if [[ -f "$JWT_FILE" ]]; then
  # shellcheck source=/dev/null
  source "$JWT_FILE"
  JWT_LINE="TROVESUITE__JWT__SECRET_KEY=${TROVESUITE_JWT_SECRET:-}"
fi

cat >"$OUT" <<EOF
# Generated by pull-azure-dev-env.sh — do not commit
# Source: $APP ($RG)

APP__CONNECTION_STRING=${CONN}
${JWT_LINE}
# ZELOSHR_API_BASE=http://localhost:8000
EOF

chmod 600 "$OUT" 2>/dev/null || true

MASKED="$(echo "$CONN" | sed -E 's#(postgresql://[^:]+:)[^@]+#\1***#')"
echo "Wrote ${OUT}"
echo "  APP__CONNECTION_STRING=${MASKED}"
if [[ -n "$JWT_LINE" ]]; then
  echo "  TROVESUITE__JWT__SECRET_KEY=<from .jwt-secret.local>"
else
  echo "  (no .jwt-secret.local — add TROVESUITE__JWT__SECRET_KEY manually or generate on CA)"
fi
echo ""
echo "Next: ./scripts/local-dev/run-api-live-db.sh   # local API → dev Postgres"
echo "      ./scripts/local-dev/smoke-dev.sh smoke  # hit deployed or local base"
